name: Publish to PyPI and GitHub Releases

on:
  push:
    branches:
      - master
    paths:
      - pyproject.toml

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Check pypi versions
        uses: maybe-hello-world/pyproject-check-version@v4
        id: versioncheck
        with:
          pyproject-path: "./pyproject.toml"

      - name: Publish to PyPI
        if: ${{ steps.versioncheck.outputs.local_version_is_higher == 'true' }}
        run: |
          uv build
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}

      - name: Release
        if: ${{ steps.versioncheck.outputs.local_version_is_higher == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.versioncheck.outputs.local_version }}
          name: ${{ steps.versioncheck.outputs.local_version }}
